---

- name: Unpin Microsoft taskbar items
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ loop_user }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ loop_item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton
    - TaskbarDa
    - TaskbarMn
    - ShowCopilotButton
  loop_control:
    loop_var: loop_item
