---

- name: "Unpin Microsoft taskbar items for user {{ loop_user }}"
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ loop_user }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ loop_item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton #  Hide cotrana button
    - TaskbarDa # Hide Widgets button
    - TaskbarMn # Hide Chat button
    - ShowCopilotButton # Hide Copilot button
  loop_control:
    loop_var: loop_item
  failed_when: false
